### ISSUE TITLE
Adding Electrolux 9kg Ultimate Care Heat Pump Dryer

### ISSUE THREAD

**Issue by jampat000** [tomekkleszcz/homebridge-electrolux-devices#10]
**Is your feature request related to a problem? Please describe:**
No problems

**Describe the solution you'd like:**
I would like to see the Electrolux 9kg Ultimate Care Heat Pump Dryer added to the supported appliances please.

**Describe alternatives you've considered:**
No alternatives

**Additional context:**
N/A

**Comment by BIDA2023** [comment]
@jampat000 Any luck on heat pump dryer, i am looking for it Aswell , Appreciate any info on it . Thank you
