### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by Panic135** [tomekkleszcz/homebridge-electrolux-devices#19]
Please can you add a switch into the settings that will allow us to turn off logging? The polling and update messages every 30 seconds can clog the logs very quickly!

absolutely love the plugin though! Thanks!

![IMG_3981](https://github.com/tomekkleszcz/homebridge-electrolux-devices/assets/79020305/60068fd2-b8f6-427f-9f9b-3454af56b24b)

**Comment by tomekkleszcz** [comment]
Hi @Panic135 I've changed the log level to debug for these messages. I'll release the new version in a couple of minutes. I'm closing this issue for now. Will reopen if it won't help.
