### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by rafalkarolczyk** [tomekkleszcz/homebridge-electrolux-devices#28]
**Describe The Bug:**

**To Reproduce:**

**Expected behavior:**

**Logs:**

:37 PM] [homebridge-electrolux-devices] Restarting Process...
[10/17/2023, 4:10:38 PM] [homebridge-electrolux-devices] Launched child bridge with PID 76964
[10/17/2023, 4:10:38 PM] Registering platform 'homebridge-electrolux-devices.HomebridgeElectroluxDevices'
[10/17/2023, 4:10:38 PM] [homebridge-electrolux-devices] Loaded homebridge-electrolux-devices v0.0.4-beta.1 child bridge successfully
[10/17/2023, 4:10:38 PM] [homebridge-electrolux-devices] Signing in to Electrolux...
[10/17/2023, 4:10:38 PM] Homebridge v1.6.1 (HAP v0.11.1) (homebridge-electrolux-devices) is running on port 51826.
[10/17/2023, 4:10:38 PM] [homebridge-electrolux-devices] Couldn't not sign in to Electrolux!
[10/17/2023, 4:10:38 PM] [homebridge-electrolux-devices] Discovering devices...

/usr/local/lib/node_modules/homebridge-electrolux-devices/node_modules/axios/lib/core/settle.js:19
    reject(new AxiosError(
           ^
AxiosError: Request failed with status code 401
    at settle (/usr/local/lib/node_modules/homebridge-electrolux-devices/node_modules/axios/lib/core/settle.js:19:12)
    at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/homebridge-electrolux-devices/node_modules/axios/lib/adapters/http.js:572:11)
    at IncomingMessage.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1408:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
[10/17/2023, 4:10:38 PM] [homebridge-electrolux-devices] Child bridge process ended
[10/17/2023, 4:10:38 PM] [homebridge-electrolux-devices] Process Ended. Code: 1, Signal: null

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by stenmic** [comment]
I've been getting the same error for 2 days

**Comment by elanorTS** [comment]
Same error here as well

**Comment by xszuflax** [comment]
Same here it looks it is related to node.js version. Once upgraded to 18. or 20. error shows up. If you downgrade node to 16. it will be OK but homebridge just stoped supporting node 16 :-/

**Comment by rafalkarolczyk** [comment]
Can it be fixed?

**Comment by horhokokki** [comment]
Same here.

**Comment by virtuality222** [comment]
Same issue here

**Comment by nfin1te** [comment]
Same issue for me aswell

**Comment by nfin1te** [comment]
Is this project dead? I came here, because AEG/Electrolux apparently discontinued their old API and "Homebridge AEG Wellbeing", the plugin I used until now, recommended this plugin - but the code hasn't been touched since 4 months by now.

**Comment by hevalito** [comment]
Same here. Can't login.

**Comment by hevalito** [comment]
`AxiosError: Request failed with status code 401
    at settle (/homebridge/node_modules/homebridge-electrolux-devices/node_modules/axios/lib/core/settle.js:19:12)
    at IncomingMessage.handleStreamEnd (/homebridge/node_modules/homebridge-electrolux-devices/node_modules/axios/lib/adapters/http.js:585:11)
    at IncomingMessage.emit (node:events:529:35)
    at endReadableNT (node:internal/streams/readable:1368:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)`

**Comment by adamwych** [comment]
FYI this is the issue: https://github.com/scotthovestadt/gigya/issues/64. Gigya SDK used by this plugin is severely outdated and contains an old certificate, so all Gigya login requests fail. Manually replacing the certificate with the new one makes it work fine.

1. Navigate to where you installed `homebridge-electrolux-devices` (in my case that's here: C:\Users\USERNAME\AppData\Roaming\npm\node_modules\homebridge-electrolux-devices)
2. Go to `node_modules\gigya\assets`.
3. Replace `cacert.pem` with this one: https://github.com/SAP/gigya-python-sdk/blob/main/cacert.pem

You can check where the plugin is installed by running `npm list -g`.

**Comment by nfin1te** [comment]
> FYI this is the issue: [scotthovestadt/gigya#64](https://github.com/scotthovestadt/gigya/issues/64). Gigya SDK used by this plugin is severely outdated and contains an old certificate, so all Gigya login requests fail. Manually replacing the certificate with the new one makes it work fine.
> 
>     1. Navigate to where you installed `homebridge-electrolux-devices` (in my case that's here: C:\Users\USERNAME\AppData\Roaming\npm\node_modules\homebridge-electrolux-devices)
> 
>     2. Go to `node_modules\gigya\assets`.
> 
>     3. Replace `cacert.pem` with this one: https://github.com/SAP/gigya-python-sdk/blob/main/cacert.pem
> 
> 
> You can check where the plugin is installed by running `npm list -g`.
> 
> Note: I don't know if the accessories will actually respond since I don't own any, but _login_ does work after replacing the certificate.

You, Sir, are an absolute beauty. Tested, works and my AX9 does reply and work as intended after your suggested fix! 

Thank you very much!

**Comment by horhokokki** [comment]
Not working with bebian. Still says cant login.

**Comment by rafalkarolczyk** [comment]
macOS - works! Tank you nfin1te.

**Comment by virtuality222** [comment]
Thank you so, SO, much! I had given up on this plugin. Confirmed to fix it on my Raspberry pi. —Jonathan Gulbrandsenphone:	+46 73 996 79 84email:	***@***.***:	jonathan.gulbrandsen.netweb:	jgulbrandsen.net20 dec. 2023 kl. 11:04 skrev Adam Wychowaniec ***@***.***>:﻿
FYI this is the issue: scotthovestadt/gigya#64. Gigya SDK used by this plugin is severely outdated and contains an old certificate, so all Gigya login requests fail. Manually replacing the certificate with the new one makes it work fine.

Navigate to where you installed homebridge-electrolux-devices (in my case that's here: C:\Users\USERNAME\AppData\Roaming\npm\node_modules\homebridge-electrolux-devices)
Go to node_modules\gigya\assets.
Replace cacert.pem with this one: https://github.com/SAP/gigya-python-sdk/blob/main/cacert.pem

You can check where the plugin is installed by running npm list -g.

**Comment by hevalito** [comment]
Just tested it - Doesn't work. 
Synology DSM with Dockerized Homebridge...

**Comment by horhokokki** [comment]
I edited platform.js in 
/var/lib/homebridge/node_modules/homebridge-electrolux-devices/dist/

adding the line to top of file.. after const section:
process.env['NODE_TLS_REJECT_UNAUTHORIZED'] = '0';

And I added some logging to get more errors to figure something out for signin function:
        catch (e) {
            this.log.warn('not sign in to Electrolux!');
            this.log.warn("stack: ",e.stack);
            this.log.warn("message: ",e.message);
        }

**Comment by pandizajner** [comment]
Thanks @virtuality222 
Replacing the `cacert.pem` file in Gigya did a job for me and now it successfully conencts to Electrolux.

What I did is, in HB Terminal:
```cd node_modules/homebridge-electrolux-devices/node_modules/gigya/assets
rm cacert.pem
wget -O cacert.pem https://raw.githubusercontent.com/SAP/gigya-python-sdk/main/cacert.pem
```
and thereafter I restarted the HB. I hope it helps!

**Comment by gillesdemey** [comment]
I've published a new version of this plugin (called `@gillesdemey/homebridge-electrolux-devices`) with an updated CA cert, feel free to use that one until we can get this one updated :)

You can simply search for it in homebridge; config files are compatible so you should be able to just copy over your old config.

**Comment by tomekkleszcz** [comment]
Sorry for late response here, the new version has been released which fixes the issue. Please let me know if it works for you, otherwise I'll reopen this issue.

**Comment by nfin1te** [comment]
> Sorry for late response here, the new version has been released which fixes the issue. Please let me know if it works for you, otherwise I'll reopen this issue.

Yes, works for me! Thank you very much!
