### ISSUE TITLE
Support for UltimateHome 500

### ISSUE THREAD

**Issue by Marxxu3ru** [tomekkleszcz/homebridge-electrolux-devices#32]
Support for UltimateHome 500

**Comment by tomekkleszcz** [comment]
Hi @Marxxu3ru Would you able to change your password to the Electrolux app and send me credentials to my email tomekkleszcz[at]icloud.com? Since I don't own this appliance, I'm unable to support it without your help.

**Comment by Marxxu3ru** [comment]
Sorry, I'm using Home Assistant.

**Comment by tomekkleszcz** [comment]
OK, If you decide to switch back to Homebridge let me know, so I can update the plugin.
