### ISSUE TITLE
Couldn't login the electrolux

### ISSUE THREAD

**Issue by skeljp** [tomekkleszcz/homebridge-electrolux-devices#5]
Hi, I've installed your plugin with Great Thanks, however, the plugin causes a reboot loop.
I've checked the ID/pass several times, and re-make the Electrolux account, but it doesn't solve it.
I have left the logs as below and please give me advice to solve the issue if you found.
The Electrolux device is Pure A9.

```
Logs

[11/07/2023, 01:45:00] [homebridge-electrolux-devices] Signing in to Electrolux...
[11/07/2023, 01:45:01] Homebridge v1.6.1 (HAP v0.11.1) (homebridge-electrolux-devices) is running on port 32113.
[11/07/2023, 01:45:02] [homebridge-electrolux-devices] Couldn't not sign in to Electrolux!
[11/07/2023, 01:45:02] [homebridge-electrolux-devices] Discovering devices...
3Address 192.168.68.144, 
4EOJ [ 15, 32, 1 ]
4EOJ [ 2, 145, 1 ]
3Address 192.168.68.101
4EOJ [ 3, 187, 1 ]
Initializing e817a4a9-64e0-408e-9efd-da2462d1040e 192.168.68.xxx [ 2, 145, 1 ]
Initialized brightness e817a4a9-64e0-408e-9efd-da2462d1040e 0
4EOJ [ 2, 145, 2 ]
Initializing 1003e392-6616-4b1a-b71c-5e5f1d2ca8be 192.168.68.xxx [ 2, 145, 2 ]

/var/lib/homebridge/node_modules/homebridge-electrolux-devices/node_modules/axios/lib/core/settle.js:19
    reject(new AxiosError(
           ^
AxiosError: Request failed with status code 500
    at settle (/var/lib/homebridge/node_modules/homebridge-electrolux-devices/node_modules/axios/lib/core/settle.js:19:12)
    at IncomingMessage.handleStreamEnd (/var/lib/homebridge/node_modules/homebridge-electrolux-devices/node_modules/axios/lib/adapters/http.js:570:11)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
```

```
Config.json

    "email": "xxxxxxxxxx",
    "password": "xxxxxxxxxxx",
    "pollingInterval": 30,
    "carbonDioxideSensorAlarmValue": 1000,
    "platform": "HomebridgeElectroluxDevices",
    "_bridge": {
        "username": "0E:XX:XX:XX:XX:XX",
        "port": 00000

```

```
Environment:
GMT+0900 (JAPAN)
OS	Raspbian GNU/Linux Bullseye (11)
hostname	homebridge
IPv4 (wlan0)	192.168.xxx.xxx
IPv6 (wlan0)	xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Node.js バージョン	[v18.16.0](https://homebridge.io/w/JTKEF)
ユーザ	pi
lacation	/var/lib/homebridge
config	/var/lib/homebridge/config.json
plugin	/var/lib/homebridge/node_modules
Service mode	Yes
```

**Comment by tomekkleszcz** [comment]
Hi @skeljp ,

The plugin was initially written for usage in the EU region. I'll try to add support for different regions in the following days.

**Comment by skeljp** [comment]
Wow, Thanks for your quick responce. I've left the proxymanlog in the link as below, password is my account ID.
if it doesn't work, please let me know.
[https://Mashineru.quickconnect.to/d/s/uLQPjOJyKzNzuYaio6XM0KQvvUn1Rqya/2dmDpz0KVIWU9CYHFYDvaP-g-IdnVaaB-PbHAA_nZlQo](url)

**Comment by tomekkleszcz** [comment]
@skeljp Thank you! It seems Electrolux uses the EU region for devices based in Japan. You can remove this file right now as it may contain some sensitive data. The last thing I'm missing are requests made to gigya.com. Could you please send me the logs for the "accounts.xxx.gigya.com"? I need just the URL to get to know what Gigya endpoint you are using right now to log in.

**Comment by skeljp** [comment]
Hi, Thanks for check it, I've removed the link. 
I have searched "gigya" in the ploxyman, however, there seems no entries. If my behavior is wrong, please let me know. 
Thanks.

**Comment by tomekkleszcz** [comment]
> Hi, Thanks for check it, I've removed the link. I have searched "gigya" in the ploxyman, however, there seems no entries. If my behavior is wrong, please let me know. Thanks.

Could you clear the logs, open the Electrolux app and send me the screen of the URLs list?

**Comment by skeljp** [comment]
Does it work?

![image](https://github.com/tomekkleszcz/homebridge-electrolux-devices/assets/121911587/f5cedeed-65f6-41d4-8456-4bf0d459231b)

**Comment by skeljp** [comment]
Thanks for step by step supporting. I,ve done it and found "gigya.com" in the log. 
the endpoint ID is "au1"
https://i.imgur.com/2ixUqUt.png
please check it.

**Comment by tomekkleszcz** [comment]
> Thanks for step by step supporting. I've done it and found "gigya.com" in the log. the endpoint ID is "au1" https://i.imgur.com/2ixUqUt.png please check it.

Thanks! I'll implement the support for regions today, and I'll send you what you need to do in order to log in.

**Comment by tomekkleszcz** [comment]
@skeljp Please download the `0.0.4-beta.1` version and in the config below the `pollingInterval` please add the following line: `"region": "au",`.

Please let me know if that worked for you, thanks!

**Comment by skeljp** [comment]
Thanks for quick job! I've installed it however the issue was not solved...
Logs
```
[15/07/2023, 11:25:04] [homebridge-electrolux-devices] Child bridge process ended
[15/07/2023, 11:25:04] [homebridge-electrolux-devices] Process Ended. Code: 1, Signal: null
[15/07/2023, 11:25:11] [homebridge-electrolux-devices] Restarting Process...
[15/07/2023, 11:25:14] [homebridge-electrolux-devices] Launched child bridge with PID 1690
[15/07/2023, 11:25:14] Registering platform 'homebridge-electrolux-devices.HomebridgeElectroluxDevices'
[15/07/2023, 11:25:15] [homebridge-electrolux-devices] Loaded homebridge-electrolux-devices v0.0.4-beta.1 child bridge successfully
[15/07/2023, 11:25:15] [homebridge-electrolux-devices] Signing in to Electrolux...
[15/07/2023, 11:25:15] Homebridge v1.6.1 (HAP v0.11.1) (homebridge-electrolux-devices) is running on port 32113.
[15/07/2023, 11:25:16] [homebridge-electrolux-devices] Couldn't not sign in to Electrolux!
[15/07/2023, 11:25:16] [homebridge-electrolux-devices] Discovering devices...

/var/lib/homebridge/node_modules/homebridge-electrolux-devices/node_modules/axios/lib/core/settle.js:19
    reject(new AxiosError(
           ^
AxiosError: Request failed with status code 500
    at settle (/var/lib/homebridge/node_modules/homebridge-electrolux-devices/node_modules/axios/lib/core/settle.js:19:12)
    at IncomingMessage.handleStreamEnd (/var/lib/homebridge/node_modules/homebridge-electrolux-devices/node_modules/axios/lib/adapters/http.js:570:11)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
```
Confings
```
{
    "email": "XXXXXXXXXX@gmail.com",
    "password": "XXXXXXXXXXX",
    "region": "au",
    "pollingInterval": 30,
    "carbonDioxideSensorAlarmValue": 1000,
    "_bridge": {
        "username": "XX:XX:XX:XX:XX:XX",
        "port": 32113
    },
    "platform": "HomebridgeElectroluxDevices"
}
```
When I recreated the account in the  EU country, e.g. Germany, for testing purposes, the plugin worked flawlessly. Hence, the plugin's core functionality goes fine in my environment.

BTW, I encountered another issue, and I would like to bring it to your attention;
Despite setting the fan speed on the iPhone to its maximum level, the fan speed on Pure A9 only reaches a maximum of 5. The correct maximum value is 9.

**Comment by tomekkleszcz** [comment]
> Thanks for quick job! I've installed it however the issue comes again... Logs
> 
> ```
> [15/07/2023, 11:25:04] [homebridge-electrolux-devices] Child bridge process ended
> [15/07/2023, 11:25:04] [homebridge-electrolux-devices] Process Ended. Code: 1, Signal: null
> [15/07/2023, 11:25:11] [homebridge-electrolux-devices] Restarting Process...
> [15/07/2023, 11:25:14] [homebridge-electrolux-devices] Launched child bridge with PID 1690
> [15/07/2023, 11:25:14] Registering platform 'homebridge-electrolux-devices.HomebridgeElectroluxDevices'
> [15/07/2023, 11:25:15] [homebridge-electrolux-devices] Loaded homebridge-electrolux-devices v0.0.4-beta.1 child bridge successfully
> [15/07/2023, 11:25:15] [homebridge-electrolux-devices] Signing in to Electrolux...
> [15/07/2023, 11:25:15] Homebridge v1.6.1 (HAP v0.11.1) (homebridge-electrolux-devices) is running on port 32113.
> [15/07/2023, 11:25:16] [homebridge-electrolux-devices] Couldn't not sign in to Electrolux!
> [15/07/2023, 11:25:16] [homebridge-electrolux-devices] Discovering devices...
> 
> /var/lib/homebridge/node_modules/homebridge-electrolux-devices/node_modules/axios/lib/core/settle.js:19
>     reject(new AxiosError(
>            ^
> AxiosError: Request failed with status code 500
>     at settle (/var/lib/homebridge/node_modules/homebridge-electrolux-devices/node_modules/axios/lib/core/settle.js:19:12)
>     at IncomingMessage.handleStreamEnd (/var/lib/homebridge/node_modules/homebridge-electrolux-devices/node_modules/axios/lib/adapters/http.js:570:11)
>     at IncomingMessage.emit (node:events:525:35)
>     at endReadableNT (node:internal/streams/readable:1359:12)
>     at processTicksAndRejections (node:internal/process/task_queues:82:21)
> ```
> 
> Confings
> 
> ```
> {
>     "email": "XXXXXXXXXX@gmail.com",
>     "password": "XXXXXXXXXXX",
>     "region": "au",
>     "pollingInterval": 30,
>     "carbonDioxideSensorAlarmValue": 1000,
>     "_bridge": {
>         "username": "XX:XX:XX:XX:XX:XX",
>         "port": 32113
>     },
>     "platform": "HomebridgeElectroluxDevices"
> }
> ```
> 
> When I re-created Electrolux account in the EU country, e.g. Germany, for testing purposes, the plugin worked flawlessly. Hence, the plugin's core functionality goes fine in my environment.
> 
> BTW, I'd like to let you know that encountered another issue; Despite setting the fan speed on the Homekit to its maximum level, the fan speed on Pure A9 only reaches a maximum of 5. The correct maximum value is 9. pls see the link as below: https://i.imgur.com/fgzsXNS.jpg

Thank you for your investigation. I'll create a Japanese account and I'll try to debug it by myself. 

When it comes to the maximum fan speed, I'll open the separate issue for that.

**Comment by rafalkarolczyk** [comment]
Hi, I have the same problem: "Couldn't not sign in to Electrolux!".
Since today...may be electrolux has changed something...
My regon EU...Poland

**Comment by tomekkleszcz** [comment]
@rafalkarolczyk Your issue is probably related to old certificate found in gigya library. Please try to use the new 0.0.5 version to log in.
