### ISSUE TITLE
Please add support for Electrolux Well A5 / AEG AX5 air purifiers

### ISSUE THREAD

**Issue by andreybernovski** [tomekkleszcz/homebridge-electrolux-devices#56]
Hi!

it would be great to add support for the A5 air purifier. It’s pretty much identical to the A7 you already support, but doesn’t have the ionization function as far as I know. It also lacks the temperature, humidity and CO2 sensors. At least those are not exposed to the native app and won’t probably be exposed to HomeKit.

**Comment by tomekkleszcz** [comment]
Hi @andreybernovski Would you able to change your password to the Electrolux app and send me credentials to my email tomekkleszcz[at]icloud.com? Since I don't own this appliance, I'm unable to support it without your help.

**Comment by andreybernovski** [comment]
> Hi @andreybernovski Would you able to change your password to the Electrolux app and send me credentials to my email tomekkleszcz[at]icloud.com? Since I don't own this appliance, I'm unable to support it without your help.

@tomekkleszcz sent you an email. Thanks a lot for helping out :)

**Comment by tomekkleszcz** [comment]
@andreybernovski The new `0.2.0` version should be available on NPM shortly. Please update the plugin and let me know if it works for you. I did some testing and it worked just fine. I don't expect any bugs, as this air purifier is missing advanced features.

**Comment by andreybernovski** [comment]
@tomekkleszcz you are amazing! Thanks!

My only comment is that it seems the way you expose the device to HomeKit doesn't report the Air Quality, even though it shown in the native app
![IMG_65908E3018DD-1](https://github.com/tomekkleszcz/homebridge-electrolux-devices/assets/165729167/87f5fa1a-94e0-4922-ac3d-6719e0c48713)
